server:
  port: ${port}
spring:
  main:
    allow-bean-definition-overriding: true
  application:
    name: products.worker
    cloud:
      aws:
        region:
          static: sa-east-1
        credentials:
          access-key: ${AWS_ACCESS_KEY_ID}
          secret-key: ${AWS_SECRET_ACCESS_KEY}
        sqs:
          endpoint: http://localhost:4566
aws:
  endpoint: http://localhost:4566
  access-key-id: ${AWS_ACCESS_KEY_ID}
  secret-key: ${AWS_SECRET_ACCESS_KEY}
  region: sa-east-1
  dynamodb:
    region: sa-east-1
    table: marketplace-test
  sqs:
    region: sa-east-1
    create-queue:
      queue-url: "https://localhost.localstack.cloud:4566/000000000000/product-creation-test"
      max-message: 10
      wait-time: 5
    update-queue:
      queue_url: "https://localhost.localstack.cloud:4566/000000000000/product-creation-test"
      max_message: 50
      wait_time: 5
    delete-queue:
      queue_url: "https://localhost.localstack.cloud:4566/000000000000/product-creation-test"
      max_message: 50
      wait_time: 5